FROM ghcr.io/roadrunner-server/roadrunner:2025.1.6 as roadrunner
FROM php:8.4-cli

RUN --mount=type=bind,from=mlocati/php-extension-installer:2,source=/usr/bin/install-php-extensions,target=/usr/local/bin/install-php-extensions \
     install-php-extensions @composer-2 opcache zip intl sockets protobuf imap redis pdo_pgsql pdo_mysql

COPY --from=roadrunner /usr/bin/rr /usr/local/bin/rr
EXPOSE 80/tcp

WORKDIR /app

COPY rr.yaml /docker-entrypoint.d/rr.yaml

RUN if [ -f config/bundles.php ]; then \
    if ! grep -q "Baldinof\\\\\\\\RoadRunnerBundle\\\\\\\\BaldinofRoadRunnerBundle" config/bundles.php; then \
        sed -i '/return \\[/a \\    Baldinof\\\\RoadRunnerBundle\\\\BaldinofRoadRunnerBundle::class => ["all" => true],' config/bundles.php; \
    fi \
fi

RUN composer require baldinof/roadrunner-bundle:^3.0 --with-all-dependencies
RUN composer require spiral/roadrunner-cli --dev --with-all-dependencies
RUN composer update --with-all-dependencies

CMD ["rr", "serve", "-c", "/docker-entrypoint.d/rr.yaml"]
