services:
  php:
    build:
      context: ../../franken
      args:
        PHP_VERSION: 8.4
        ANTISLEEP_ENV: local
        PHP_INI_ENV: development
    container_name: symfony_php
    ports:
      - "8080:80"
    volumes:
      - ../../app/:/app/
    networks:
      app_net:
