services:
  php:
    build:
      context: ../../roadrunner
      args:
        PHP_VERSION: 8.4
    container_name: symfony_php
    ports:
      - "8080:80"
    volumes:
      - ../../app/:/app/
    networks:
      app_net: