FROM dunglas/frankenphp:1-php8.4

RUN apt-get update && apt-get install -y \
    mc \
    htop \
    libzip-dev \
    libpng-dev \
    libpq-dev \
    supervisor \
    libicu-dev \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN docker-php-ext-install zip pdo pdo_pgsql pdo_mysql intl sockets gd
RUN pecl install xdebug && docker-php-ext-enable xdebug

RUN mkdir -p /app/var/log

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /app

CMD sh -c "frankenphp php-server --root /app/public public/index.php"
